### ISSUE TITLE
Memory issue when changing models

### ISSUE THREAD

**Issue by Mist-Hunter** [kestr31/docker-stable-diffusion-webui#5]
Thank you for this great Docker container!

It took me a couple days to find this repo, apologies if I missed it, but from your Docker hub page, there doesn't seem to be a link: https://hub.docker.com/r/kestr3l/stable-diffusion-webui

I've noticed that as I change models, my memory keeps climbing and climbing. It's like all the models are getting loaded in RAM, I'll see the main process eating 20+Gigs of ram (which is my VM limit). This might not relate to the container, and more to automatic1111, curious if you have any ideas either way.

Thanks again for the container!

**Comment by kestr31** [comment]
I am sorry that could not make a comment on issue you made several months ago.
It is really grateful that this container could help you well. I do not know what caused it, but it is very nice that it is fixed for now.
Thank you for your feedback.

**Comment by Mist-Hunter** [comment]
I should have left a comment, but I've come to realize that the memory behavior is just how automatic1111 works when changing models. Thanks again.
