### ISSUE TITLE
run the webui repo in code?not UI?

### ISSUE THREAD

**Issue by henbucuoshanghai** [kestr31/docker-stable-diffusion-webui#6]

**Comment by kestr31** [comment]
I could not unserstand what you said. If you mean the method to deploy this container simply:

1. clone this repo (On Naitive Linux. WSL needs additional works)
2. Enter the directory of this repo and run `setup.sh` (You must have docker and nvidia container toolkit installed)
3. All Done.

I hope this can help.

**Comment by henbucuoshanghai** [comment]
but i dont want to use the UI ,I only need the code
how?

**Comment by henbucuoshanghai** [comment]
use the scripts API for the sd-WEBUI？

**Comment by kestr31** [comment]
If you only want to use API not with UI, you can simply modify `webui-user.sh` referencing [CLI argument documentation](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings) of A1111. And simply add port settings on `docker-compose.yml` like example of `<DESIRED_PORT>:7861`.

**Comment by henbucuoshanghai** [comment]
kind answer,wehere is the demo ?tks

**Comment by henbucuoshanghai** [comment]
i canot  understand the code in  webui-user.sh   .....tks

**Comment by kestr31** [comment]
I just updated the repository and I hope this would be much easier for you to deploy your own SD-webui. I am closing this issue but if you need any help, feel free to make a comment. Thanks.
